name: Deprecation Warning

on:
  pull_request:
    types:
      - opened

jobs:
  post-deprecation-message:
    runs-on: self-hosted

    steps:
      - name: Add deprecation message as a comment
        uses: actions/github-script@v6
        with:
          script: |
            const message = `
            ### 🚨 This Repository is Deprecated
            This repository is no longer actively maintained. Please use the new repository for future updates and contributions:
            
            👉 **[New Repository](https://github.com/melisource/fury_mobile-dependencies-allowlist)** 👈
            
            If you have any questions, refer to the new repository or contact the maintainers.
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: message,
            });
